### PR TITLE
create draft

### PR DESCRIPTION
**Pull request by dominik-kern**
minimal example of buckling to demonstrate numerical continuation (arc-length method)

### CODE REVIEW

**Comment by nagelt** [comment]
many thanks, @dominik-kern . You have a real talent for making this stuff entertaining : )

A few points on the wish list:

- [ ] add the images promised in the TODOs
- [ ] rename $x$ to an angular coordinate, e.g. $\phi$
- [ ] re-scale the x-axes in the plots to $\pi$ or $\pi/2$
- [ ] add some visual representation (ellipsoid) for the arc length in the iterative method. Maybe also of how it avoids the issue you point to in script 04a (the horizontal tangent / singular Jacobian)

For the final point I'm wondering about this (in the context of future extensions to OGS): I've traditionally thought of it in F-u space where a scalar multiplier is applied to the external loads. Your example can be interpreted in terms of an analogous M-phi space (well, at least for non-zero angles). Maybe this can help to draw the connection to the more general application of the method as a scaling of external loads? I'm not sure, though. We may also look at it as simply scaling the gravitational loading. Neither really helps this example, but works towards the generalization ...

**Comment by nagelt** [comment]
@chleh you may be interested in this, too

**Comment by dominik-kern** [comment]
One point is still missing, the demonstration how the arc-length constraint avoids a singular Jacobian. Coming next.

**Comment by dominik-kern** [comment]
From my point of view the example is complete now.

The stability analysis of multi-DoF systems is done similarly by scaling the load with a scalar parameter. Since most continua are elastic (in a certain range), in addition there may be imperfections,  the branching is not that "sharp" but happens, too.

**Pull request merged**
